
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Sidebar} from '@/components/ui/sidebar';
import {AppSidebarContent} from '@/components/SidebarContent';
import {SidebarProvider} from '@/components/ui/sidebar'; // Import SidebarProvider

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider> {/* Wrap content with SidebarProvider */}
          <div className="flex">
            <Sidebar collapsible="icon">
              <AppSidebarContent />
            </Sidebar>
            <div className="flex-1 p-4">{children}</div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}

